[package]
name = "translators"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
tokio = { version = "1.38.0", features = ["macros"] }
urlencoding = "2.1.3"
html-escape = "0.2.13"
regex = "1.10.5"
