[package]
name = "translators"
version = "0.1.0"
edition = "2021"
authors = ["charl1e7"]
description = "Free Google Translator, Deepl without API key and limits."
license = "MIT"
repository = "https://github.com/charl1e7/rust-translators"

[dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
tokio = { version = "1.38.0", features = ["macros"] }
urlencoding = "2.1.3"
html-escape = "0.2.13"
regex = "1.10.5"

